name: Deploy TED Bot with SAM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'master' || 'master' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show directory structure
        run: |
          echo "Root directory listing:"
          ls -la
          echo "TED bot directory listing:"
          ls -la
          echo "TED bot contents:"
          ls -la *.js *.mjs *.json 2>/dev/null || echo "No JS/MJS/JSON files found"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Python for SAM CLI
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install dependencies
        run: |
          npm ci || npm install

      - name: Build SAM application
        run: |
          sam build

      - name: Deploy to AWS
        run: |
          sam deploy \
            --stack-name ted-bot-${{ github.ref_name }} \
            --region ${{ vars.AWS_REGION }} \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --resolve-s3 \
            --parameter-overrides \
              OPENAIAPIKEY="${{ secrets.OPENAI_API_KEY }}" \
              ESAPIKEY="${{ secrets.ES_API_KEY }}" \
              ESENDPOINT="${{ vars.ES_ENDPOINT }}" \
              ESINDEXNAME="${{ vars.ES_INDEX_NAME }}" \
              EMBEDDINGMODEL="${{ vars.EMBEDDING_MODEL }}"

      - name: Get Lambda URL
        run: |
          URL=$(aws cloudformation describe-stacks \
            --stack-name ted-bot-${{ github.ref_name }} \
            --region ${{ vars.AWS_REGION }} \
            --query 'Stacks[0].Outputs[?OutputKey==`TEDBotFunctionUrl`].OutputValue' \
            --output text)
          echo "Lambda Function URL: $URL"

      - name: Deploy summary
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "### Stack Information" >> $GITHUB_STEP_SUMMARY
          echo "- **Stack Name**: ted-bot-${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Region**: ${{ vars.AWS_REGION }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          URL=$(aws cloudformation describe-stacks \
            --stack-name ted-bot-${{ github.ref_name }} \
            --region ${{ vars.AWS_REGION }} \
            --query 'Stacks[0].Outputs[?OutputKey==`TEDBotFunctionUrl`].OutputValue' \
            --output text)
          echo "### Function URL" >> $GITHUB_STEP_SUMMARY
          echo "- **URL**: $URL" >> $GITHUB_STEP_SUMMARY
